import copy
import numpy as np
import ants
import os
import argparse
import nibabel as nib

def get_freesurfer_LUT(subj_dir):
    with open(os.path.join(subj_dir, 'freesurfer/FreeSurferColorLUT.txt'), 'r') as f:
        LUT = f.readlines()
    
    LUT = list(filter(lambda x: len(x.split())>=6 and x[0]!= '#', LUT))
    label_dict = dict(list(map(lambda x: (int(x.split()[0]), x.split()[1].strip()), LUT)))
    full_lut = dict(list(map(lambda x: (int(x.split()[0]), {'name':x.split()[1].strip(), 'R':x.split()[2], 'G':x.split()[3], 'B':x.split()[4], 'A':x.split()[5]}), LUT)))
    return label_dict, full_lut

def get_cerebellum_labels(subj_dir):
    with open(os.path.join(subj_dir, 'cerebellum/LABELS.csv'), 'r') as f:
        cerebellum_labels = f.readlines()
    
    cerebellum_labels = list(map(lambda x: x.strip().split(','), cerebellum_labels[1:]))
    cerebellum_labels = list(map(lambda x: (int(x[0]), x[1].strip()), cerebellum_labels))
    cerebellum_labels = dict(cerebellum_labels)
    
    # add background
    cerebellum_labels[0] = 'Unknown'
    return cerebellum_labels

def get_hippocampus_labels(subj_dir):
    with open(os.path.join(subj_dir, 'hippunfold/LABELS.txt'), 'r') as f:
        hippocampus_labels = f.readlines()

    hippocampus_labels = list(map(lambda x: x.strip().split(','), hippocampus_labels[1:]))
    hippocampus_labels = list(map(lambda x: (int(x[0]), x[1].strip()), hippocampus_labels))
    hippocampus_labels = dict(hippocampus_labels)
    
    # add background
    hippocampus_labels[0] = 'Unknown'
    return hippocampus_labels

def get_schaefer_LUT(subj_dir, nparcels):
    with open(os.path.join(subj_dir, f'freesurfer/Schaefer_LUT/Schaefer2018_{nparcels}Parcels_17Networks_order_LUT.txt'), 'r') as f:
        LUT = f.readlines()
    
    LUT = list(filter(lambda x: len(x.split())>=6 and x[0]!= '#', LUT))
    label_dict = dict(list(map(lambda x: (int(x.split()[0]), x.split()[1].strip()), LUT)))
    full_lut = dict(list(map(lambda x: (int(x.split()[0]), {'name':x.split()[1].strip(), 'R':x.split()[2], 'G':x.split()[3], 'B':x.split()[4], 'A':x.split()[5]}), LUT)))
    return label_dict, full_lut

def get_resampled_image(subj_dir, img_path):
    # takes a label volume generated by freesurfer and transforms it in subject space
    
    orig = ants.image_read(os.path.join(subj_dir, 'raw/T1.nii.gz'))
    new = ants.image_read(os.path.join(subj_dir, img_path))
    
    new = ants.resample_image_to_target(new, orig, interp_type='genericLabel')
    
    return new.numpy().astype(int)

def relabel_image(img, old_labels, new_labels):
    assert len(old_labels)==len(new_labels)
    
    assert img.min()>=0
    max_label = max([img.max(), max(old_labels)])
    tmp_labels = np.arange(max_label+1).astype(int)
    
    tmp_labels[old_labels] = new_labels
    return np.copy(tmp_labels[img])

def invert_dict(dictionary):
    return dict(map(lambda x: (x[1], x[0]), dictionary.items()))

def relabel_vector(vector, old_labels, new_labels):
    assert min(vector)>=0, "Input vector contains negative labels, can't handle that yet."

    keys = np.array(list(old_labels.keys()))
    values = invert_dict(new_labels)
    values = [values[x] for x in old_labels.values()]

    lookup = np.repeat(-1, max(keys)+1)
    lookup[keys] = values
    return lookup[vector]


if __name__ == "__main__":
    ################ input parsing ##############
    parser = argparse.ArgumentParser(
        description="Process subject data to create a comprehensive atlas.",
        formatter_class=argparse.RawTextHelpFormatter
    )

    # 1. Define the Subject Folder Argument
    parser.add_argument(
        '--subject_dir',
        type=str,
        required=True,
        help='Path to the subject folder (e.g., /SUBJECTS/<subjectname>/)'
    )

    # Parse the arguments from the command line
    args = parser.parse_args()

    # Call your main processing function
    subj_dir = args.subject_dir

    try:
        os.mkdir(os.path.join(subj_dir, 'atlas/hippunfold_surf'))
        os.mkdir(os.path.join(subj_dir, 'atlas/freesurfer_surf'))
        os.mkdir(os.path.join(subj_dir, 'atlas/cerebellum_surf'))
    except FileExistsError:
        print('Atlases already detected in subject folder, you should delete the atlas folder before running this module!')

    T1 = nib.load(os.path.join(subj_dir, 'raw/T1.nii.gz'))
    fsLUT = get_freesurfer_LUT(subj_dir)[1]

    for nparcels in [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]:
        # initialize atlas and LUT
        newLabels = {}
        newLUT = {}

        atlas = np.zeros_like(T1.get_fdata(), dtype=int)

        newLabels[0] = 'Unknown'
        newLUT[0] = copy.deepcopy(fsLUT[0])
        
        #################################################### CEREBELLUM ATLAS
        cerebellum = nib.load(os.path.join(subj_dir,'cerebellum/nonlinear_gray_labels.nii.gz')).get_fdata().astype(int)

        old_labels = [(x,'cerebellum_'+get_cerebellum_labels(subj_dir)[x].replace(' ', '_')) for x in np.unique(cerebellum).tolist() if get_cerebellum_labels(subj_dir)[x]!='Unknown']
        old_labels = list(zip(*old_labels))

        cereb_labels = dict(zip(list(range(601, 625)), old_labels[1]))
        newLabels.update(cereb_labels) 
        for key, val in cereb_labels.items():
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLUT[key]['name'] = val

        # create label file for surface
        if not os.path.exists(os.path.join(subj_dir, 'atlas/cerebellum_surf/cereb_labels.npy')):
            GM_lab = np.load(os.path.join(subj_dir, 'surfaces/cereb_inner_original_labels.npy'))

            GM_lab = relabel_vector(GM_lab, dict(zip(*old_labels)), cereb_labels)
            np.save(os.path.join(subj_dir, 'atlas/cerebellum_surf/cereb_labels.npy'), GM_lab)
        
        cerebellum = relabel_image(cerebellum, list(old_labels[0]), list(range(601, 625)))

        atlas[np.isin(cerebellum, list(range(601, 625)))] = cerebellum[np.isin(cerebellum, list(range(601, 625)))]

        cerebflag = 601
        
        #################################################### ASEG ATLAS
        aseg = get_resampled_image(subj_dir, f'freesurfer/mri/schaefer{nparcels}_aparc+aseg.mgz')

        # aseg labels that need to be kept
        labels_to_keep = ['Left-Caudate', 'Left-Putamen', 'Left-Pallidum', 'Left-Accumbens-area', 'Left-VentralDC', 'Right-Caudate', 'Right-Putamen', 'Right-Pallidum', 'Right-Accumbens-area', 'Right-VentralDC', 'Fornix', 'CC_Posterior', 'CC_Mid_Posterior', 'CC_Central', 'CC_Mid_Anterior', 'CC_Anterior']
        to_keep = [key for (key, val) in get_freesurfer_LUT(subj_dir)[0].items() if val in labels_to_keep]

        # check if LUT did not change
        assert len(labels_to_keep)==len(to_keep)

        atlas[np.isin(aseg, to_keep)] = aseg[np.isin(aseg, to_keep)]

        for key in to_keep:
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLabels[key] = copy.deepcopy(fsLUT[key]['name'])

        asegflag = min(to_keep)
        ccflag = 250
        
        ##################################################### SCHAEFER CORTICAL ATLAS
        schaefer_LUT = get_schaefer_LUT(subj_dir, nparcels)[1]
        to_keep = np.unique(aseg[(aseg>1000)&(aseg<3000)&(aseg!=2000)]).tolist()

        for key in to_keep:
            newLUT[key] = copy.deepcopy(schaefer_LUT[key])
            newLabels[key] = copy.deepcopy(schaefer_LUT[key]['name'])

        fs_lab = np.load(os.path.join(subj_dir, f'surfaces/freesurfer_lh_middle_original_labels_{nparcels}.npy'))
        _, _, values = nib.freesurfer.read_annot(os.path.join(subj_dir, f'freesurfer/label/lh.Schaefer2018_{nparcels}Parcels_17Networks_order.annot'))
        values = np.array(values).astype(str)
        values[0] = 'Unknown'
        old_labels = dict(zip(range(len(values)+1), values.tolist()))
        fs_lab = relabel_vector(fs_lab, old_labels, newLabels)
        np.save(os.path.join(subj_dir, f'atlas/freesurfer_surf/lh.{nparcels}Parcels_labels.npy'), fs_lab)
        
        fs_lab = np.load(os.path.join(subj_dir, f'surfaces/freesurfer_rh_middle_original_labels_{nparcels}.npy'))        
        _, _, values = nib.freesurfer.read_annot(os.path.join(subj_dir, f'freesurfer/label/rh.Schaefer2018_{nparcels}Parcels_17Networks_order.annot'))
        values = np.array(values).astype(str)
        values[0] = 'Unknown'
        old_labels = dict(zip(range(len(values)+1), values.tolist()))
        fs_lab = relabel_vector(fs_lab, old_labels, newLabels)
        np.save(os.path.join(subj_dir, f'atlas/freesurfer_surf/rh.{nparcels}Parcels_labels.npy'), fs_lab)

        atlas[(aseg>1000)&(aseg<3000)&(aseg!=2000)] = aseg[(aseg>1000)&(aseg<3000)&(aseg!=2000)]

        leftschaeferflag = 1001
        rightschaeferflag = 2001
        
        ##################################################### HYPOTHALAMUS ATLAS
        hypvinn = get_resampled_image(subj_dir, 'fastsurfer/mri/hypothalamus.HypVINN.nii.gz')

        # hypothalamus labels that need to be kept
        labels_to_keep = ['R-N.opticus', 'L-N.opticus', 'R-C.mammilare', 'R-Optic-tract', 'L-Optic-tract', 'L-C.mammilare', 'R-Chiasma-Opticum', 'L-Chiasma-Opticum', 'Ant-Commisure', 'Third-Ventricle', 'R-Fornix', 'L-Fornix', 'Epiphysis', 'Hypophysis', 'Infundibulum', 'Tuberal-Region', 'L-Med-Hypothalamus', 'L-Lat-Hypothalamus', 'L-Ant-Hypothalamus', 'L-Post-Hypothalamus', 'R-Med-Hypothalamus', 'R-Lat-Hypothalamus', 'R-Ant-Hypothalamus', 'R-Post-Hypothalamus']
        to_keep = [key for (key, val) in get_freesurfer_LUT(subj_dir)[0].items() if val in labels_to_keep]

        # check if LUT did not change
        assert len(labels_to_keep)==len(to_keep)

        atlas[np.isin(hypvinn, to_keep)] = hypvinn[np.isin(hypvinn, to_keep)]

        for key in to_keep:
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLabels[key] = copy.deepcopy(fsLUT[key]['name'])

        hyvinnflag = min(to_keep)

        ###################################################### BRAINSTEM ATLAS
        brstem = get_resampled_image(subj_dir, 'freesurfer/mri/brainstemSsLabels.mgz')

        # brainstem labels that need to be kept
        labels_to_keep = ['brainstem', 'DCG', 'Vermis', 'Midbrain', 'Pons', 'Medulla', 'Vermis-White-Matter', 'SCP', 'Floculus']
        to_keep = [key for (key, val) in get_freesurfer_LUT(subj_dir)[0].items() if val in labels_to_keep]


        # check if LUT did not change
        assert len(labels_to_keep)==len(to_keep)


        atlas[np.isin(brstem, to_keep)] = brstem[np.isin(brstem, to_keep)]

        for key in to_keep:
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLabels[key] = copy.deepcopy(fsLUT[key]['name'])

        brstemflag = min(to_keep)
        
        ####################################################### THALAMUS ATLAS
        thalamus = get_resampled_image(subj_dir, 'freesurfer/mri/ThalamicNuclei.mgz')

        labels_to_keep = [val for (key,val) in get_freesurfer_LUT(subj_dir)[0].items() if key in range(8103,8237)]
        to_keep = [key for (key, val) in get_freesurfer_LUT(subj_dir)[0].items() if val in labels_to_keep]


        # check if LUT did not change
        assert len(labels_to_keep)==len(to_keep)


        atlas[np.isin(thalamus, to_keep)] = thalamus[np.isin(thalamus, to_keep)]

        for key in to_keep:
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLabels[key] = copy.deepcopy(fsLUT[key]['name'])

        thalamusflag = min(to_keep)
        
        #################################################### AMYGDALA ATLAS
        ############## LEFT
        Lhippoamy = get_resampled_image(subj_dir, 'freesurfer/mri/lh.hippoAmygLabels.mgz')

        old_labels = [(x,'Left-'+get_freesurfer_LUT(subj_dir)[0][x]) for x in range(7001,7021)]
        old_labels = list(zip(*old_labels))

        amyg_labels = dict(zip(list(range(7001, 7001+len(old_labels[1]))), old_labels[1]))
        newLabels.update(amyg_labels)
        for key,val in amyg_labels.items():
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLUT[key]['name'] = val

        Lhippoamy = relabel_image(Lhippoamy, list(old_labels[0]), list(range(7001, 7001+len(old_labels[1]))))

        atlas[np.isin(Lhippoamy, list(range(7001, 7001+len(old_labels[1]))))] = Lhippoamy[np.isin(Lhippoamy, list(range(7001, 7001+len(old_labels[1]))))]

        ############## RIGHT
        Rhippoamy = get_resampled_image(subj_dir, 'freesurfer/mri/rh.hippoAmygLabels.mgz')

        old_labels = [(x,'Right-'+get_freesurfer_LUT(subj_dir)[0][x]) for x in range(7001,7021)]
        old_labels = list(zip(*old_labels))

        amyg_labels = dict(zip(list(range(7001+len(old_labels[1]), 7001+2*len(old_labels[1]))), old_labels[1]))
        newLabels.update(amyg_labels) 
        for key, val in amyg_labels.items():
            newLUT[key] = copy.deepcopy(fsLUT[key-len(old_labels[1])])
            newLUT[key]['name'] = val

        Rhippoamy = relabel_image(Rhippoamy, list(old_labels[0]), list(range(7001+len(old_labels[1]), 7001+2*len(old_labels[1]))))

        atlas[np.isin(Rhippoamy, list(range(7001+len(old_labels[1]), 7001+2*len(old_labels[1]))))] = Rhippoamy[np.isin(Rhippoamy, list(range(7001+len(old_labels[1]), 7001+2*len(old_labels[1]))))]
        
        amygflag = 7001
        
        ######################################################## HIPPOCAMPUS ATLAS
        ################ LEFT
        Lhipp = get_resampled_image(subj_dir, 'hippunfold/anat/sub-subject_hemi-L_space-cropT1w_desc-subfields_atlas-multihist7_dseg.nii.gz')

        old_labels = [(x, 'Left-'+get_hippocampus_labels(subj_dir)[x]) for x in get_hippocampus_labels(subj_dir).keys() if get_hippocampus_labels(subj_dir)[x]!='Unknown']
        old_labels = list(zip(*old_labels))

        hipp_labels = dict(zip(list(range(193, 193+len(old_labels[1]))), old_labels[1]))
        newLabels.update(hipp_labels) 
        for key, val in hipp_labels.items():
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLUT[key]['name'] = val
        
        # create label file for surfaces
        if not os.path.exists(os.path.join(subj_dir, 'atlas/hippunfold_surf/L_hipp_labels.npy')):
            surf_lab = np.load(os.path.join(subj_dir, 'surfaces/hippunfold_L_hipp_middle_original_labels.npy'))
            surf_lab = relabel_vector(surf_lab, dict(zip(*old_labels)), hipp_labels)
            np.save(os.path.join(subj_dir, 'atlas/hippunfold_surf/L_hipp_labels.npy'), surf_lab)
        
        if not os.path.exists(os.path.join(subj_dir, 'atlas/hippunfold_surf/L_dent_labels.npy')):
            surf_lab = np.load(os.path.join(subj_dir, 'surfaces/hippunfold_L_dentate_middle_original_labels.npy'))
            surf_lab = relabel_vector(surf_lab, dict(zip(*old_labels)), hipp_labels)
            np.save(os.path.join(subj_dir, 'atlas/hippunfold_surf/L_dent_labels.npy'), surf_lab)

        Lhipp = relabel_image(Lhipp, list(old_labels[0]), list(range(193, 193+len(old_labels[0]))))

        atlas[np.isin(Lhipp, list(range(193, 193+len(old_labels[0]))))] = Lhipp[np.isin(Lhipp, list(range(193, 193+len(old_labels[0]))))]

        ############### RIGHT
        Rhipp = get_resampled_image(subj_dir, 'hippunfold/anat/sub-subject_hemi-R_space-cropT1w_desc-subfields_atlas-multihist7_dseg.nii.gz')

        old_labels = [(x, 'Right-'+get_hippocampus_labels(subj_dir)[x]) for x in get_hippocampus_labels(subj_dir).keys() if get_hippocampus_labels(subj_dir)[x]!='Unknown']
        old_labels = list(zip(*old_labels))

        hipp_labels = dict(zip(list(range(193+len(old_labels[1]), 193+2*len(old_labels[1]))), old_labels[1]))
        newLabels.update(hipp_labels) 
        for key, val in hipp_labels.items():
            newLUT[key] = copy.deepcopy(fsLUT[key])
            newLUT[key]['name'] = val
        
        
        if not os.path.exists(os.path.join(subj_dir, 'atlas/hippunfold_surf/R_hipp_labels.npy')):
            surf_lab = np.load(os.path.join(subj_dir, 'surfaces/hippunfold_R_hipp_middle_original_labels.npy'))
            surf_lab = relabel_vector(surf_lab, dict(zip(*old_labels)), hipp_labels)
            np.save(os.path.join(subj_dir, 'atlas/hippunfold_surf/R_hipp_labels.npy'), surf_lab)
        
        if not os.path.exists(os.path.join(subj_dir, 'atlas/hippunfold_surf/R_dent_labels.npy')):
            surf_lab = np.load(os.path.join(subj_dir, 'surfaces/hippunfold_R_dentate_middle_original_labels.npy'))
            surf_lab = relabel_vector(surf_lab, dict(zip(*old_labels)), hipp_labels)
            np.save(os.path.join(subj_dir, 'atlas/hippunfold_surf/R_dent_labels.npy'), surf_lab)

        Rhipp = relabel_image(Rhipp, list(old_labels[0]), list(range(193+len(old_labels[0]), 193+2*len(old_labels[0]))))

        atlas[np.isin(Rhipp, list(range(193+len(old_labels[0]), 193+2*len(old_labels[0]))))] = Rhipp[np.isin(Rhipp, list(range(193+len(old_labels[0]), 193+2*len(old_labels[0]))))]
        
        hippoflag = 193
        
        ######################################################### SAVE ATLAS
        atlas = nib.Nifti1Image(atlas, T1.affine, T1.header)
        nib.save(atlas, os.path.join(subj_dir,f'atlas/atlas{nparcels}.nii.gz'))
        
        ######################################################### SAVE LABELS
        with open(os.path.join(subj_dir, f'atlas/atlas{nparcels}_labels.txt'), 'w') as f:
            for key,val in sorted(list(newLabels.items()), key=lambda x: x[0]):
                f.write(f'{key},{val}\n')
        
        ######################################################## SAVE LUT
        with open(os.path.join(subj_dir, f'atlas/atlas{nparcels}_LUT.txt'), 'w') as f:
            f.write('#No.\tLabel Name:\tR\tG\tB\tA\n')
            for key,val in sorted(newLUT.items(), key = lambda x: x[0]):
                if key == asegflag:
                    f.write('\n# Subcortical regions (from Freesurfer aseg)\n')
                if key == ccflag:
                    f.write('\n# Corpus Callosum regions (from Freesurfer aseg)\n')
                if key == brstemflag:
                    f.write('\n# Brainstem regions (from Freesurfer brainstem stream)\n')
                if key == hippoflag:
                    f.write('\n# Hippocampal regions regions (from Hippunfold)\n')
                if key == cerebflag:
                    f.write('\n# Cerebellar regions (from an high res atlas coregistered to this subject)\n')
                if key == hyvinnflag:
                    f.write('\n# Hypothalamus and nearby regions (from hypvinn included in fastsurfer)\n')
                if key == leftschaeferflag:
                    f.write(f'\n# Left cortex regions from Schaefer {nparcels}\n')
                if key == rightschaeferflag:
                    f.write(f'\n# Right cortex regions from Schaefer {nparcels}\n')
                if key == amygflag:
                    f.write('\n# Amygdala region (from Freesurfer hippoamygdala stream)\n')
                if key == thalamusflag:
                    f.write('\n# Thalamus region (from Freesurfer thalamic stream)\n')
                f.write(f'{key}\t{val['name']}\t{val['R']}\t{val['G']}\t{val['B']}\t{val['A']}\n')
    
    # easy to read labels
    aggregated_labels = [   ([0],'Unknown'),
                            ([11],'Left-Caudate'),
                            ([12],'Left-Putamen'),
                            ([13],'Left-Pallidum'),
                            ([26],'Left-Accumbens'),
                            ([28],'Left-VentralDC'),
                            ([50],'Right-Caudate'),
                            ([51],'Right-Putamen'),
                            ([52],'Right-Pallidum'),
                            ([58],'Right-Accumbens'),
                            ([60],'Right-VentralDC'),
                            ([173,174,175], 'Brainstem'),
                            ([193,194,195,196,197,198,199,200], 'Left-Hippocampus'),
                            ([201,202,203,204,205,206,207,208], 'Right-Hippocampus'),
                            ([601,602,603,604,605,606,607,608,609,610,611,612], 'Left-Cerebellum'),
                            ([613,614,615,616,617,618,619,620,621,622,623,624], 'Right-Cerebellum'),
                            ([963],'Right-Mammillary-body'),
                            ([966],'Left-Mammilary-body'),
                            ([976],'Tuberal-Region'),
                            ([977,978,979,980], 'Left-Hypothalamus'),
                            ([981,982,983,984], 'Right-Hypothalamus'),
                            (list(range(1000, 2000)), 'Left-Cortex'),
                            (list(range(2000,3000)), 'Right-Cortex'),
                            ([7001,7002,7003,7004,7005,7006,7007,7008,7009], 'Left-Amygdala'),
                            ([7010,7011,7012,7013,7014,7015,7016,7017,7018], 'Right-Amygdala'),
                            ([8103,8104,8105,8106,8108,8109,8110,8111,8112,8113,8115,8116,8118,8120,8121,8122,8123,8126,8127,8128,8129,8130,8133], 'Left-Thalamus'),
                            ([8203,8204,8205,8206,8208,8209,8210,8211,8212,8213,8215,8216,8217,8218,8220,8221,8222,8223,8226,8227,8228,8229,8230,8233], 'Right-Thalamus')]
    
    atlas = nib.load(os.path.join(subj_dir,f'atlas/atlas100.nii.gz')).get_fdata().astype(int)
    with open(os.path.join(subj_dir, f'atlas/atlas_aggregated_labels.txt'), 'w') as f:
        lab = 0
        for values, name in aggregated_labels:
            f.write(f'{lab},{name}\n')
            atlas[np.isin(atlas, values)] = lab
            lab+=1
    atlas = nib.Nifti1Image(atlas, T1.affine, T1.header)
    nib.save(atlas, os.path.join(subj_dir,f'atlas/atlas_aggregated.nii.gz'))
